services:
  - type: web
    name: ssi-digital-hub
    env: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.13
      - key: DATABASE_FROM_ENV
        value: true