# Generated by Django 6.1 on 2026-08-22 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=250)),
                ('speaker_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Reg Open', 'Registration Open'), ('Completed', 'Completed')], default='Upcoming', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('registration_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.session')),
            ],
        ),
    ]
