# Generated by Django 6.1 on 2026-08-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='session_banners/'),
        ),
    ]
