# Generated by Django 6.1 on 2026-08-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_session_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='slug',
        ),
        migrations.AddField(
            model_name='session',
            name='recording_url',
            field=models.URLField(blank=True, help_text='YouTube or Google Drive link to recorded session', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='slides_file',
            field=models.FileField(blank=True, help_text='PDF or PPT slides', null=True, upload_to='session_slides/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='department',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='speaker_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Reg Open', 'Registration Open'), ('Ongoing', 'Ongoing'), ('Past', 'Past / Completed')], default='Upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='session_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='session',
            name='venue',
            field=models.CharField(default='Google Meet', max_length=255),
        ),
    ]
