# Generated by Django 6.1 on 2026-08-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Cheat Sheet', 'Cheat Sheet'), ('Code Template', 'Code Template'), ('Study Notes', 'Study Notes'), ('Configuration', 'Configuration File'), ('External Link', 'External Link')], default='Study Notes', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources_files/')),
                ('external_url', models.URLField(blank=True, help_text='Optional link if resource is online', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
