# Generated by Django 6.1 on 2026-08-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional small thumbnail image', null=True, upload_to='resource_thumbnails/'),
        ),
    ]
